### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by Insephet** [CyCoSnag/snag_weapon_metas#4]
Followed the installation, changed a vehicleweapon.meta drastically, but it didn't change anything.

**Comment by CyCoSnag** [comment]
I'd have to test, but I've used these metas to disable all vehicle weapons so they are working. You'd also want to make sure you don't have another resource using these metas, as they can conflict and load over each other.

**Comment by jnccloud** [comment]
> I'd have to test, but I've used these metas to disable all vehicle weapons so they are working. You'd also want to make sure you don't have another resource using these metas, as they can conflict and load over each other.

Hey man, I am trying to do the same thing on the speedo4 (removing weapons). Struggling a bit. Can you share some info on how you accomplished that?
