### ISSUE TITLE
Modifying (Vanilla) Weapons Doesn't Work

### ISSUE THREAD

**Issue by Burnswood** [CyCoSnag/snag_weapon_metas#6]
For some aspects, this is less an "issue" but more of a support.

I'm attempting to modify the primary sidearms, (Pistol, Combat Pistol, etc..) but when I modify things like mag size, they don't change.

Is this normal? Is there something I can do to fix this?

**Comment by CyCoSnag** [comment]
When you edit clip sizes in the weapons.meta file, you're editing the weapon clip size without magazines. If you want to edit magazine size, find the <AttachPoints> meta for the weapon you're editing and find the name of the magazine components. For example, the WEAPON_PISTOL default magazine that is enabled is COMPONENT_PISTOL_CLIP_01, which is set to true in the metas. Setting that to false would disable that magazine from default appearing on the gun, then the magazine size change in that meta would work. You can change the settings of the COMPONENT_PISTOL_CLIP_01 by running a search in the weaponcomponents folders and changing the magazine values there for each entry of the COMPONENT_PISTOL_CLIP_01 that is found.

**Comment by Burnswood** [comment]
How could it have been so obvious! Clip component...D'OH

Thank you, I'll give that a try

**Comment by Burnswood** [comment]
Worked like a charm, thanks.
